---
- name: Wait for startup marker
  import_playbook: ./wait_for_startup_marker.yml
- name: Install and configure Docker
  import_playbook: ./install_and_configure_docker.yml
- name: Deploy NGINX and SQL Compose
  import_playbook: ./deploy_app1.yml
