---
- name: Deploy Docker Compose App (PHP nginx + mysql)
  hosts: all
  become: true
  vars:
    app_dir: /opt/app1
  tasks:
    - name: Create app directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0750"

    - name: Write environment variables to file
      ansible.builtin.copy:
        dest: "{{ app_dir }}/.env"
        mode: "0600"
        content: |
          DB_HOST=app1_db
          MYSQL_DATABASE=app1
          MYSQL_USER="user_{{ 99999 | random }}"
          MYSQL_PASSWORD="{{ lookup('password', '/dev/null', length=20, chars='ascii_letters') }}"
          MYSQL_ROOT_PASSWORD="{{ lookup('password', '/dev/null', length=20, chars='ascii_letters') }}"

    - name: Create web data directory
      ansible.builtin.file:
        path: "{{ app_dir }}/web_data"
        state: directory
        mode: "0750"

    - name: Create db data directory
      ansible.builtin.file:
        path: "{{ app_dir }}/db_data"
        state: directory
        mode: "0750"

    - name: Create db directory
      ansible.builtin.file:
        path: "{{ app_dir }}/db_data/db"
        state: directory
        mode: "0750"

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: docker/nginx_sql_compose.yml
        dest: "{{ app_dir }}/docker-compose.yml"
        mode: '0640'

    - name: Copy web nginx.conf file
      ansible.builtin.copy:
        src: web/nginx.conf
        dest: "{{ app_dir }}/web_data/nginx.conf"
        mode: '0640'

    - name: Copy web index.php file
      ansible.builtin.copy:
        src: web/index.php
        dest: "{{ app_dir }}/web_data/index.php"
        mode: '0640'

    - name: Copy web dockerfile
      ansible.builtin.copy:
        src: web/Dockerfile
        dest: "{{ app_dir }}/web_data/Dockerfile"
        mode: '0640'

    - name: Copy db init.sql file
      ansible.builtin.copy:
        src: sql/init.sql
        dest: "{{ app_dir }}/db_data/init.sql"
        mode: '0640'

    - name: Copy db dockerfile
      ansible.builtin.copy:
        src: sql/Dockerfile
        dest: "{{ app_dir }}/db_data/Dockerfile"
        mode: '0640'

    - name: Copy db entrypoint file
      ansible.builtin.copy:
        src: sql/docker-entrypoint.sh
        dest: "{{ app_dir }}/db_data/docker-entrypoint.sh"
        mode: '0640'

    - name: Bring up containers using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        build: always
        state: present
