version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_data:/usr/share/nginx/html
    depends_on:
      - db
    networks:
      - mysql_net

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GENERATE
      MYSQL_DATABASE: nginx_db
      MYSQL_USER: GENERATE
      MYSQL_PASSWORD: GENERATE
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql_net

volumes:
  db_data:
  nginx_data:

networks:
  mysql_net:
